version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"  # Change to daily for more frequent checks
    ignore:
      - dependency-name: "docker/login-action"
        versions: ["1.x"]
