# docker compose -f docker-compose-sqlite.yml up -d

version: '3.8'

services:
  webapp:
    build:   # Build from a Dockerfile
      context: .  # Use the current directory as context
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database