version: '3.8'

services:
  webapp:
    image: webapp-webapp
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database
    environment:
      MYSQL_URL: mysql://matteo:MySecureUserPassword!@database:3306/mydb  # MySQL URL
    depends_on:
      - database  # The database is started if the application is started

  database:
    image: mysql:latest  # Use the official MySQL image
    environment:
      MYSQL_ROOT_PASSWORD: MySecureRootPassword!  # Root password
      MYSQL_DATABASE: mydb  # Database name
      MYSQL_USER: matteo  # User name
      MYSQL_PASSWORD: MySecureUserPassword!  # Password for the user
    ports:
      - "3307:3306"  # MySQL port